name: PR Checks
on: [pull_request]

jobs:
  run-plogon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: goatcorp/DalamudPluginsD17
        path: manifests

    - name: Create required folders
      run: |
        mkdir output
        mkdir artifacts
        mkdir static
        mkdir work

    - name: Run Plogon
      run: |
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v "${{ github.workspace }}/work":"/work" \
        -v "${{ github.workspace }}/output":"/output" \
        -v "${{ github.workspace }}/static":"/static" \
        -v "${{ github.workspace }}/manifests":"/manifests" \
        -v "${{ github.workspace }}/artifacts":"/artifacts" \
        ghcr.io/goatcorp/plogon:latest \
        --manifest-folder="/manifests" \
        --output-folder="/output" \
        --work-folder="/work" \
        --static-folder="/static" \
        --artifact-folder="/artifact" \
        --ci \
        --actor="${{ github.actor }}"
